[workspace]
resolver = "2"
members = [
    "bc/blog/application",
    "bc/blog/domain",
    "bc/blog/infrastructure",
    "bc/blog/presentation/api",
    "bc/blog/presentation/api-graphql",
    "shared_kernel",
    "app",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Childéric <socgnachilderic@proton.me>"]

[workspace.dependencies]
anyhow = "1.0.95"
async-trait = { version = "0.1.85" }
dotenvy = "0.15.7"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
tokio = { version = "1.42.0", features = ["full"] }
uuid = { version = "1.11.0", features = ["fast-rng", "v4"] }

[profile.release]
debug = true

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
