[package]
name = "blog_infrastructure"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
blog_application = { path = "../application" }
blog_domain = { path = "../domain" }
chrono = "0.4.39"
dotenvy.workspace = true
log = "0.4.22"
serde_json.workspace = true
shared_kernel = { path = "../../../shared_kernel" }
sqlx = { version = "0.8.2", features = [
    "postgres",
    "runtime-tokio-native-tls",
    "chrono",
] }
