[package]
name = "blog_application"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
blog_domain = { path = "../domain" }
shared_kernel = { path = "../../../shared_kernel" }
