[package]
name = "shared_kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde = { workspace = true, features = ["derive"] }
shared_kernel_macro = { path = "../macros/shared_kernel" }

[features]
default = []
sqlx = ["dep:sqlx", "dep:serde_json", "chrono"]

[dependencies.sqlx]
version = "0.8.2"
optional = true
features = ["postgres", "runtime-tokio-native-tls", "chrono"]

[dependencies.serde_json]
version = "1.0.105"
optional = true

[dependencies.chrono]
version = "0.4.26"
optional = true
features = ["serde"]
