[package]
name = "blog_domain"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
shared_kernel = { path = "../../../shared_kernel" }
uuid.workspace = true
